// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsX7UQzWQHFUdZsf27gqW8Rtcr3xaG4Zw',
    appId: '1:593469651990:web:cd5cc7ea90283cd1080937',
    messagingSenderId: '593469651990',
    projectId: 'local-stuff-buy-and-sell',
    authDomain: 'local-stuff-buy-and-sell.firebaseapp.com',
    storageBucket: 'local-stuff-buy-and-sell.appspot.com',
    measurementId: 'G-Q200Z31HDC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOfswZoyFmBnc9T8n94ACOP7HQl12Utzo',
    appId: '1:593469651990:android:47f50a02426acc0d080937',
    messagingSenderId: '593469651990',
    projectId: 'local-stuff-buy-and-sell',
    storageBucket: 'local-stuff-buy-and-sell.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbPaKAypjFf0yWO5IHk7ZDZcTIKd6CMRI',
    appId: '1:593469651990:ios:3a2a8479cac491c7080937',
    messagingSenderId: '593469651990',
    projectId: 'local-stuff-buy-and-sell',
    storageBucket: 'local-stuff-buy-and-sell.appspot.com',
    iosBundleId: 'com.example.localStuffSellBuy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbPaKAypjFf0yWO5IHk7ZDZcTIKd6CMRI',
    appId: '1:593469651990:ios:3a2a8479cac491c7080937',
    messagingSenderId: '593469651990',
    projectId: 'local-stuff-buy-and-sell',
    storageBucket: 'local-stuff-buy-and-sell.appspot.com',
    iosBundleId: 'com.example.localStuffSellBuy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsX7UQzWQHFUdZsf27gqW8Rtcr3xaG4Zw',
    appId: '1:593469651990:web:f90377d2ed10077b080937',
    messagingSenderId: '593469651990',
    projectId: 'local-stuff-buy-and-sell',
    authDomain: 'local-stuff-buy-and-sell.firebaseapp.com',
    storageBucket: 'local-stuff-buy-and-sell.appspot.com',
    measurementId: 'G-ZKBJ7G2LXR',
  );
}
